TARGET = iphone:4.2
TARGET_CXX = xcrun -sdk iphoneos clang++
include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = GRTestImporter
GRTestImporter_FILES = GRTestImporter.m
GRTestImporter_INSTALL_PATH = /Library/Gremlin/Plugins

include $(THEOS_MAKE_PATH)/bundle.mk
