include $(THEOS)/makefiles/common.mk

TWEAK_NAME = GremlinSupport
GremlinSupport_FILES = GremlinSupport.xm
GremlinSupport_CFLAGS += -I../include
GremlinSupport_PRIVATE_FRAMEWORKS = AppSupport

include $(THEOS_MAKE_PATH)/tweak.mk
