include $(THEOS)/makefiles/common.mk

TWEAK_NAME = GRDocumentImportProxy
GRDocumentImportProxy_FILES = proxy.xm
GRDocumentImportProxy_PRIVATE_FRAMEWORKS = AppSupport
GRDocumentImportProxy_CFLAGS += -I../include

include $(THEOS_MAKE_PATH)/tweak.mk
