include $(THEOS)/makefiles/common.mk

TWEAK_NAME = GRDocumentImportProxy
GRDocumentImportProxy_FILES = proxy.xm
GRDocumentImportProxy_PRIVATE_FRAMEWORKS = AppSupport

include $(THEOS_MAKE_PATH)/tweak.mk
