include @@THEOS@@/makefiles/common.mk

BUNDLE_NAME = @@PROJECTNAME@@
@@PROJECTNAME@@_FILES = @@PROJECTNAME@@.m
@@PROJECTNAME@@_INSTALL_PATH = /Library/Gremlin/Plugins

include $(THEOS_MAKE_PATH)/bundle.mk
