/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright  (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AddressBook.framework/AddressBook
 */

#import <Foundation/NSObject.h>

@interface ABVCardParser : NSObject

- (id)initWithData:(id)data;
- (CFArrayRef)peopleAndProperties:(const CFArrayRef*)properties;
- (id)sortedPeopleAndProperties:(const CFArrayRef*)properties;

@end

