include $(THEOS)/makefiles/common.mk

TWEAK_NAME = GRDocumentImportRedirect
GRDocumentImportRedirect_FILES = redirect.xm
GRDocumentImportRedirect_PRIVATE_FRAMEWORKS = AppSupport SpringBoardServices

SUBPROJECTS = proxy

include $(THEOS_MAKE_PATH)/tweak.mk
include $(THEOS_MAKE_PATH)/aggregate.mk
